repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies:
          - gpxpy>=1.6.2
          - geopandas>=1.0.1
          - shapely>=2.0.6
          - pyproj>=3.6.1
          - pyarrow>=17.0.0
          - osmium>=4.0.2
          - pandas>=2.2.2
          - pydantic>=2.8.2
          - pydantic-settings>=2.3.4
          - pyyaml>=6.0.2
          - typer>=0.12.3
          - tqdm>=4.66.4
          - rich>=13.7.1
